name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v1.1.0

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Buld and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: somerp/geoserver
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
